module.exports = {
  FRAME_RATE: 25,
  GRID_SIZE: 12,
  STEP: 5,
  SPACE_STEP: 10,
  MISSILE_STEP: 10,
  ASTEROID_STEP: 10,
  GAME_WIDTH: 1000,
  GAME_HEIGHT: 600,
  ASTEROID_VALUE: 10,
  GAME_OVER_REASONS: {
    1: "ALL DEAD",
    2: "TIMER ENDED",
  },
}
