module.exports = {
    NEW_GAME: "NEW_GAME",
    JOIN_GAME: "JOIN_GAME",
    JOIN_GAME_ACCEPTED: "JOIN_GAME_ACCEPTED",
    GAME_STATE_UPDATE: "GAME_STATE_UPDATE",
    START_GAME: "START_GAME",
    GAME_OVER: "GAME_OVER",
    TOO_MANY_PLAYERS: "TOO_MANY_PLAYERS",
    UNKNOWN_CODE: "UNKNOWN_CODE",
    KEY_DOWN: "KEY_DOWN",
    KEY_UP: "KEY_UP",
}