module.exports = {
    NEW_GAME: "NEW_GAME",
    JOIN_GAME: "JOIN_GAME",
    JOIN_GAME_ACCEPTED: "JOIN_GAME_ACCEPTED",
    PLAYER_ADDED: "PLAYER_ADDED",
    PLAYER_REMOVED: "PLAYER_REMOVED",
    GAME_STATE_UPDATE: "GAME_STATE_UPDATE",
    GAME_ACTIVE: "GAME_ACTIVE",
    START_GAME: "START_GAME",
    GAME_OVER: "GAME_OVER",
    TOO_MANY_PLAYERS: "TOO_MANY_PLAYERS",
    UNKNOWN_CODE: "UNKNOWN_CODE",
    KEY_DOWN: "KEY_DOWN",
    KEY_UP: "KEY_UP",
    CLEAR_CANVAS: "CLEAR_CANVAS",
    DISCONNECT: "disconnect"
}