const events = {

    // frontend mutations
    NEW_GAME: "NEW_GAME",
    JOIN_GAME: "JOIN_GAME",
    JOIN_GAME_ACCEPTED: "JOIN_GAME_ACCEPTED",
    PLAYER_ADDED: "PLAYER_ADDED",
    PLAYER_REMOVED: "PLAYER_REMOVED",
    GAME_STATE_UPDATE: "GAME_STATE_UPDATE",
    GAME_ACTIVE: "GAME_ACTIVE",
    COUNTDOWN: "COUNTDOWN",
    START_GAME: "START_GAME",
    GAME_OVER: "GAME_OVER",
    ROUND_OVER: "ROUND_OVER",
    TOO_MANY_PLAYERS: "TOO_MANY_PLAYERS",
    UNKNOWN_CODE: "UNKNOWN_CODE",
    ROUND_ACTIVE: "ROUND_ACTIVE",
    KEY_DOWN: "KEY_DOWN",
    KEY_UP: "KEY_UP",
    CLEAR_CANVAS: "CLEAR_CANVAS",
    LOAD_LEVEL: "LOAD_LEVEL",
    DISCONNECT: "disconnect",

    // new frontend mutations
    SET_GAME_TYPE: "SET_GAME_TYPE",
    CREATE_GAME: "CREATE_GAME",
    START_ROUND: "START_ROUND",
    DISPLAY_MSG: "DISPLAY_MSG",
    REMOVE_PLAYER: "REMOVE_PLAYER",
    ADD_PLAYER: "ADD_PLAYER",

    //backend events which call gameStore actions

    BACKEND_NEW_GAME: "BACKEND_NEW_GAME",
    BACKEND_JOIN_GAME_ACCEPTED: "BACKEND_JOIN_GAME_ACCEPTED",
    BACKEND_GAME_ACTIVE: "BACKEND_GAME_ACTIVE",
    BACKEND_PLAYER_ADDED: "BACKEND_PLAYER_ADDED",
    BACKEND_PLAYER_REMOVED: "BACKEND_PLAYER_REMOVED",
    BACKEND_START_ROUND: "BACKEND_START_ROUND",
    BACKEND_ROUND_ACTIVE: "BACKEND_ROUND_ACTIVE"



}


module.exports = { ...events }