module.exports = {

    // frontend mutations
    CREATE_GAME: "CREATE_GAME",
    JOIN_GAME: "JOIN_GAME",
    DISCONNECT: "disconnect",

    ADD_PLAYER: "ADD_PLAYER",
    REMOVE_PLAYER: "REMOVE_PLAYER",

    GAME_STATE_UPDATE: "GAME_STATE_UPDATE",
    START_ROUND: "START_ROUND",
    END_ROUND: "END_ROUND",
    ROUND_ACTIVE: "ROUND_ACTIVE",
    GAME_ACTIVE: "GAME_ACTIVE",
    
    COUNTDOWN: "COUNTDOWN",
    GAME_OVER: "GAME_OVER",

    ROUND_OVER: "ROUND_OVER", //**** */
    TOO_MANY_PLAYERS: "TOO_MANY_PLAYERS",
    UNKNOWN_CODE: "UNKNOWN_CODE",

    KEY_DOWN: "KEY_DOWN",
    KEY_UP: "KEY_UP",

    LOAD_LEVEL: "LOAD_LEVEL",
    SET_GAME_TYPE: "SET_GAME_TYPE",
    DISPLAY_MSG: "DISPLAY_MSG",
    PLAYER_DEAD: "PLAYER_DEAD",

    //backend events which call gameStore actions
    BACKEND_ADD_PLAYER: "BACKEND_ADD_PLAYER",
    BACKEND_REMOVE_PLAYER: "BACKEND_REMOVE_PLAYER",
    BACKEND_START_ROUND: "BACKEND_START_ROUND",
    BACKEND_ROUND_ACTIVE: "BACKEND_ROUND_ACTIVE",
    BACKEND_KEY_DOWN: "BACKEND_KEY_DOWN",
    BACKEND_KEY_UP: "BACKEND_KEY_UP",
    BACKEND_PLAYER_DEAD: "BACKEND_PLAYER_DEAD",



}
