module.exports = {
  FRAME_RATE:  60,
  GRID_SIZE: 5,
  STEP: 5,
  SPACE_STEP: 6,
  MISSILE_STEP: 5,
  ASTEROID_STEP: 3,
  GAME_WIDTH: 1000,
  SEQUENCE_LENGTH: 1000,
  GAME_HEIGHT: 600,
  ASTEROID_VALUE: 10,
  ROUND_TIME: 30,
  GAME_OVER_REASONS: {
    1: "ALL DEAD",
    2: "TIMER ENDED",
  },
}
