# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  app:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
    env:
      SERVER: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "*** Installing backend dependencies ***"
      - run: cd backend && npm i
      - run: echo "*** Restarting backend service ***"
      - run: pm2 restart backend
      - run: echo "*** Installing frontend dependencies ***"
      - run: cd frontend && npm i
      - run: echo "*** Building frontend ***"
      - run: cd frontend && npm run build
  #  - run: npm test
