# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
jobs:
  app:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: cd app && npm i

      #Backend
      - run: cd app && npm run tsc-build-backend
      - run: cd app/jsBackend && npm i
      #- run: pm2 start app/jsBackend/backend/server.js --name=starshiproyal-backend
      - run: pm2 restart starshiproyal-backend

      #Frontend
      - run: cd app && npm run build
      - run: rm -rf /var/www/starshiproyal/dist
      - run: cd app && mv dist /var/www/starshiproyal/dist
